import type { Metadata } from "next";
import "./globals.css";
import { Playfair_Display, DM_Sans, Outfit, Teko, Montserrat } from "next/font/google";

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-playfair",
});

const teko = Teko({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-teko",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-montserrat",
});

const dm = DM_Sans({
  subsets: ["latin"],
  weight: ["300","400", "500", "600", "700"],
  variable: "--font-geist-sans",
});

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-geist-mono",
});


export const metadata: Metadata = {
  title: "Ease Origin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfair.variable} ${dm.variable} ${outfit.variable} ${teko.variable} ${montserrat.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
